# MySQL database
mysql:
  image: ${DOCKERHUB_REPOSITORY}/${DOCKERHUB_MYSQL_IMAGE}
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATADIR: ${MYSQL_DATADIR}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
    - ${MYSQL_VOLUME}:${MYSQL_DATADIR}
  hostname: mysql
  restart: always
  ports:
    - "3306:3306"


# Apache web server with PHP, grunt and Moodle + Omero modules
apache:
  image: ${DOCKERHUB_REPOSITORY}/${DOCKERHUB_APACHE_IMAGE}
  volumes:
    - ${WWW_VOLUME}:${APACHE_WWW_ROOT}
    - ${MOODLE_DATA_VOLUME}:${MOODLE_DATA_DIR}
    - ${MOODLE_LOG_VOLUME}:${MOODLE_LOG_DIR}
  hostname: moodle
  restart: always
  links:
    - mysql
  ports:
    - "80:80"
    - "443:443"
  dns:
    - 8.8.8.8
    # add other DNS if you need

# Init container
init:
  image: ${DOCKERHUB_REPOSITORY}/moodle-init
  environment:
    MOODLE_WWW_ROOT: ${MOODLE_WWW_ROOT}
  volumes:
    - ${WWW_VOLUME}:${APACHE_WWW_ROOT}
