#!/bin/bash

source ../config.sh

mysqldump -h ${MYSQL_HOST} \
          -u ${MYSQL_USER} \
          -p${MYSQL_PASSWORD}  \
          ${MYSQL_DATABASE} \
          > ${MYSQL_BACKUPS_DIR}/$(echo "$(date +'%d%m%Y-%H%M%S%3N').sql")
